import 'package:blockchain_utils/blockchain_utils.dart';
import 'package:on_chain/ethereum/src/models/log_entry.dart';
import 'package:on_chain/utils/utils/number_utils.dart';

/// Represents the receipt of an Ethereum transaction.
class TransactionReceipt {
  /// The hash of the block where the transaction was included.
  final String? blockHash;

  /// The block number where the transaction was included.
  final int? blockNumber;

  /// The address of the contract created, if applicable.
  final String? contractAddress;

  /// The total gas used in the block, including gas used by other transactions.
  final int? cumulativeGasUsed;

  /// The effective gas price of the transaction.
  final int? effectiveGasPrice;

  /// The gas used by this specific transaction.
  final int? gasUsed;

  /// The transaction type.
  final int type;

  /// The sender's address.
  final String from;

  /// A bloom filter for the logs of the transaction.
  final String logsBloom;

  /// The status of the transaction.
  final bool? status;

  /// The recipient's address, if it's a contract creation.
  final String? to;

  /// The hash of the transaction.
  final String transactionHash;

  /// The index of the transaction within the block.
  final int? transactionIndex;

  /// The list of log entries generated by the transaction.
  final List<LogEntry> logs;

  String get finalFee {
    final gasUsed = this.gasUsed;
    final effectiveGasPrice = this.effectiveGasPrice;
    if (gasUsed == null || effectiveGasPrice == null) return "0";
    return AmountConverter.eth
        .toAmount(BigInt.from(gasUsed) * BigInt.from(effectiveGasPrice));
  }

  /// Creates a new instance of the [TransactionReceipt] class.
  const TransactionReceipt({
    required this.blockHash,
    required this.blockNumber,
    this.contractAddress,
    required this.cumulativeGasUsed,
    required this.effectiveGasPrice,
    required this.from,
    required this.gasUsed,
    required this.logsBloom,
    required this.status,
    required this.to,
    required this.transactionHash,
    required this.transactionIndex,
    required this.type,
    required this.logs,
  });

  /// Creates a [TransactionReceipt] instance from a JSON map.
  factory TransactionReceipt.fromJson(Map<String, dynamic> json) {
    final List<LogEntry>? logs = (json.valueAsList<List?>("logs"))
        ?.map((e) => LogEntry.fromJson(e))
        .toList();
    return TransactionReceipt(
        logs: logs ?? [],
        blockHash: json.valueAs("blockHash"),
        blockNumber: PluginIntUtils.tryHexToInt(json['blockNumber']),
        contractAddress: json.valueAs("contractAddress"),
        cumulativeGasUsed:
            PluginIntUtils.tryHexToInt(json['cumulativeGasUsed']),
        effectiveGasPrice:
            PluginIntUtils.tryHexToInt(json['effectiveGasPrice']),
        from: json.valueAs("from"),
        gasUsed: PluginIntUtils.tryHexToInt(json['gasUsed']),
        logsBloom: json.valueAs("logsBloom"),
        status: PluginIntUtils.tryHexToBool(json['status']),
        to: json.valueAs("to"),
        transactionHash: json.valueAs("transactionHash"),
        transactionIndex: PluginIntUtils.tryHexToInt(json['transactionIndex']),
        type: PluginIntUtils.hexToInt(json['type']));
  }

  /// Converts the [TransactionReceipt] instance to a JSON map.
  Map<String, dynamic> toJson() {
    return {
      'blockHash': blockHash,
      'blockNumber':
          blockNumber != null ? '0x${blockNumber!.toRadixString(16)}' : null,
      'contractAddress': contractAddress,
      'cumulativeGasUsed': cumulativeGasUsed != null
          ? '0x${cumulativeGasUsed!.toRadixString(16)}'
          : null,
      'effectiveGasPrice': effectiveGasPrice != null
          ? '0x${effectiveGasPrice!.toRadixString(16)}'
          : null,
      'from': from,
      'gasUsed': gasUsed != null ? '0x${gasUsed!.toRadixString(16)}' : null,
      'logsBloom': logsBloom,
      'status': status != null ? (status! ? '0x1' : '0x0') : null,
      'to': to,
      'transactionHash': transactionHash,
      'transactionIndex': transactionIndex != null
          ? '0x${transactionIndex!.toRadixString(16)}'
          : null,
      'type': '0x${type.toRadixString(16)}',
      'logs': logs.map((log) => log.toJson()).toList(),
    }.notNullValue;
  }

  /// Returns a string representation of the [TransactionReceipt] object.
  @override
  String toString() {
    return '''
      TransactionReceipt${toJson()} 
    ''';
  }
}
